require("baphled.plugins.remaps.packer")
require("baphled.plugins.remaps.lsp")
require("baphled.plugins.remaps.git")
require("baphled.plugins.remaps.telescope")
require("baphled.plugins.remaps.trouble")
require("baphled.plugins.remaps.neotest")
require("baphled.plugins.remaps.dap")
require("baphled.plugins.remaps.nvimtree")

require("baphled.plugins.remaps.common")
require("baphled.plugins.remaps.tab")
require("baphled.plugins.remaps.spell")
require("baphled.plugins.remaps.cloak")
require("baphled.plugins.remaps.session")
require("baphled.plugins.remaps.harpoon")
