require("baphled.autocommand.git")
require("baphled.autocommand.markdown")
require("baphled.autocommand.startup")
require("baphled.autocommand.json")
require("baphled.autocommand.lsp")
require("baphled.autocommand.packer")
