require("baphled.config.which-key.lsp")
require("baphled.config.which-key.git")
require("baphled.config.which-key.gitsigns")
require("baphled.config.which-key.telescope")
require("baphled.config.which-key.trouble")
require("baphled.config.which-key.undotree")
require("baphled.config.which-key.lazy")
require("baphled.config.which-key.neotest")
require("baphled.config.which-key.dap")
require("baphled.config.which-key.nvimtree")
require("baphled.config.which-key.oil")
require("baphled.config.which-key.commentary")
require("baphled.config.which-key.zen")

require("baphled.config.which-key.common")
require("baphled.config.which-key.tab")
require("baphled.config.which-key.spell")
require("baphled.config.which-key.cloak")
require("baphled.config.which-key.session")
require("baphled.config.which-key.harpoon")
require("baphled.config.which-key.spectre")
require("baphled.config.which-key.obsidian")

require("baphled.config.which-key.molten")
require("baphled.config.which-key.quarto")


require("baphled.config.which-key.codecompanion")
